"""add_lop_tables

Revision ID: b287a51b8b41
Revises: b2c3d4e5f6a7
Create Date: 2026-04-21 08:08:15.457992

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b287a51b8b41'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lop_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('original_lop_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('adjusted_lop_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lop_overrides_business_id'), 'lop_overrides', ['business_id'], unique=True)
    op.create_index(op.f('ix_lop_overrides_company_id'), 'lop_overrides', ['company_id'], unique=False)
    op.create_table('lop_policies',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('working_days_per_month', sa.Integer(), nullable=False),
    sa.Column('use_calendar_days', sa.Boolean(), nullable=False),
    sa.Column('late_grace_count', sa.Integer(), nullable=False),
    sa.Column('lates_per_half_day', sa.Integer(), nullable=False),
    sa.Column('apply_lop_on_absent', sa.Boolean(), nullable=False),
    sa.Column('round_to_half_day', sa.Boolean(), nullable=False),
    sa.Column('max_lop_days_per_month', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_lop_policy_company')
    )
    op.create_index(op.f('ix_lop_policies_business_id'), 'lop_policies', ['business_id'], unique=True)
    op.create_index(op.f('ix_lop_policies_company_id'), 'lop_policies', ['company_id'], unique=False)
    op.create_table('lop_records',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_working_days', sa.Integer(), nullable=False),
    sa.Column('days_present', sa.Integer(), nullable=False),
    sa.Column('days_absent', sa.Integer(), nullable=False),
    sa.Column('days_on_approved_leave', sa.Integer(), nullable=False),
    sa.Column('late_count', sa.Integer(), nullable=False),
    sa.Column('lop_from_absence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lop_from_lates', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_lop_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('override_id', sa.String(length=36), nullable=True),
    sa.Column('final_lop_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('per_day_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_lop_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['override_id'], ['lop_overrides.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_id', 'year', 'month', name='uq_lop_record_emp_month')
    )
    op.create_index(op.f('ix_lop_records_business_id'), 'lop_records', ['business_id'], unique=True)
    op.create_index(op.f('ix_lop_records_company_id'), 'lop_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_lop_records_employee_id'), 'lop_records', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_applications_job_stage'), table_name='applications')
    op.drop_index(op.f('ix_attendance_approved'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_daily'), table_name='attendance')
    op.drop_index(op.f('ix_audit_logs_entity_timeline'), table_name='audit_logs')
    op.drop_index(op.f('ix_candidates_company_email'), table_name='candidates')
    op.drop_index(op.f('ix_employees_branch_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_designation_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_leave_balances_tracking'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_requests_approved_by'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_emp_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_notifications_user_read'), table_name='notifications')
    op.drop_index(op.f('ix_payroll_items_payment_status'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_run_emp'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_runs_period'), table_name='payroll_runs')
    op.drop_index(op.f('ix_performance_reviews_emp_year'), table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_reviewer'), table_name='performance_reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_performance_reviews_reviewer'), 'performance_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_performance_reviews_emp_year'), 'performance_reviews', ['employee_id', 'review_year'], unique=False)
    op.create_index(op.f('ix_payroll_runs_period'), 'payroll_runs', ['company_id', 'period_month', 'period_year'], unique=False)
    op.create_index(op.f('ix_payroll_items_run_emp'), 'payroll_items', ['payroll_run_id', 'employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_items_payment_status'), 'payroll_items', ['payment_status'], unique=False)
    op.create_index(op.f('ix_notifications_user_read'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_leave_requests_emp_status'), 'leave_requests', ['employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_leave_requests_approved_by'), 'leave_requests', ['approved_by'], unique=False)
    op.create_index(op.f('ix_leave_balances_tracking'), 'leave_balances', ['employee_id', 'leave_type_id', 'year'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['company_id', 'manager_id'], unique=False)
    op.create_index(op.f('ix_employees_designation_id'), 'employees', ['company_id', 'designation_id'], unique=False)
    op.create_index(op.f('ix_employees_branch_id'), 'employees', ['company_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_candidates_company_email'), 'candidates', ['company_id', 'email'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_timeline'), 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_attendance_daily'), 'attendance', ['company_id', 'attendance_date', 'employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_approved'), 'attendance', ['company_id', 'is_approved'], unique=False)
    op.create_index(op.f('ix_applications_job_stage'), 'applications', ['job_posting_id', 'current_stage'], unique=False)
    op.drop_index(op.f('ix_lop_records_employee_id'), table_name='lop_records')
    op.drop_index(op.f('ix_lop_records_company_id'), table_name='lop_records')
    op.drop_index(op.f('ix_lop_records_business_id'), table_name='lop_records')
    op.drop_table('lop_records')
    op.drop_index(op.f('ix_lop_policies_company_id'), table_name='lop_policies')
    op.drop_index(op.f('ix_lop_policies_business_id'), table_name='lop_policies')
    op.drop_table('lop_policies')
    op.drop_index(op.f('ix_lop_overrides_company_id'), table_name='lop_overrides')
    op.drop_index(op.f('ix_lop_overrides_business_id'), table_name='lop_overrides')
    op.drop_table('lop_overrides')
    # ### end Alembic commands ###
