"""add_basic_salary_total_deductions

Revision ID: e9e088a493b5
Revises: add_holidays_visa
Create Date: 2026-04-12 15:29:41.645878

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e088a493b5'
down_revision: Union[str, None] = 'add_holidays_visa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('holiday_type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', 'name', name='uq_holiday_company_date_name')
    )
    op.create_index(op.f('ix_holidays_business_id'), 'holidays', ['business_id'], unique=True)
    op.create_index(op.f('ix_holidays_company_id'), 'holidays', ['company_id'], unique=False)
    op.create_index(op.f('ix_holidays_country'), 'holidays', ['country'], unique=False)
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=False)
    op.create_index(op.f('ix_holidays_state'), 'holidays', ['state'], unique=False)
    op.add_column('employees', sa.Column('visa_status', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('visa_type', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('visa_expiry_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('passport_number', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('passport_expiry_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_employees_visa_expiry_date'), 'employees', ['visa_expiry_date'], unique=False)
    op.add_column('payroll_items', sa.Column('basic_salary', sa.Float(), nullable=False))
    op.add_column('payroll_items', sa.Column('total_deductions', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_items', 'total_deductions')
    op.drop_column('payroll_items', 'basic_salary')
    op.drop_index(op.f('ix_employees_visa_expiry_date'), table_name='employees')
    op.drop_column('employees', 'nationality')
    op.drop_column('employees', 'passport_expiry_date')
    op.drop_column('employees', 'passport_number')
    op.drop_column('employees', 'visa_expiry_date')
    op.drop_column('employees', 'visa_type')
    op.drop_column('employees', 'visa_status')
    op.drop_index(op.f('ix_holidays_state'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_country'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_company_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_business_id'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
